warehouse:
  type: sql
  status: planned
  config:
    driver: postgresql
    host: db.internal
    port: '5432'
    database: dwh
    table: orders
  created_at: '2026-09-07T20:56:24.886194+00:00'
  updated_at: '2026-09-07T20:56:24.886194+00:00'
finance_data:
  type: csv
  status: active
  config:
    path: sample_data/WS_DER_OTC_TOV_csv_col.csv
    delimiter: ','
    header_row: '1'
    encoding: utf-8
    quotechar: '"'
    skip_rows: '0'
  created_at: '2026-09-08T08:38:51.369011+00:00'
  updated_at: '2026-09-08T08:38:51.369011+00:00'
ref_dimension_codes:
  type: csv
  status: active
  config:
    path: sample_data/ref_dimension_codes.csv
    delimiter: ','
    header_row: '1'
    encoding: utf-8
    quotechar: '"'
    skip_rows: '0'
  created_at: '2026-09-08T11:17:30.142379+00:00'
  updated_at: '2026-09-09T09:14:47.070147+00:00'
feed_status:
  type: csv
  status: active
  config:
    path: sample_data/feed_status.csv
    delimiter: ','
    header_row: '1'
    encoding: utf-8
    quotechar: '"'
    skip_rows: '0'
  created_at: '2026-09-08T11:17:30.157978+00:00'
  updated_at: '2026-09-09T09:14:47.080186+00:00'
recon_euc_positions:
  type: csv
  status: active
  config:
    path: sample_data/recon_euc_positions.csv
    delimiter: ','
    header_row: '1'
    encoding: utf-8
    quotechar: '"'
    skip_rows: '0'
  created_at: '2026-09-08T11:17:30.173633+00:00'
  updated_at: '2026-09-09T09:14:47.111484+00:00'
recon_gl_match:
  type: csv
  status: active
  config:
    path: sample_data/recon_gl_match.csv
    delimiter: ','
    header_row: '1'
    encoding: utf-8
    quotechar: '"'
    skip_rows: '0'
  created_at: '2026-09-08T11:17:30.187824+00:00'
  updated_at: '2026-09-09T09:14:47.127107+00:00'
recon_gl_break:
  type: csv
  status: active
  config:
    path: sample_data/recon_gl_break.csv
    delimiter: ','
    header_row: '1'
    encoding: utf-8
    quotechar: '"'
    skip_rows: '0'
  created_at: '2026-09-08T11:17:30.219084+00:00'
  updated_at: '2026-09-09T09:14:47.142698+00:00'
